main: mb.mizinkobusters.elysium.Main
name: MiningGame
version: 1.0.0
author: Mizinkobusters

commands:
  xpranking:
    permission: mining.op
  randomstone:
      permission: mining.op
  start:
      permission: mining.op

permissions:
  mining.op:
    default: op