main: mb.mizinkobusters.elysium.Main
name: MiningGame
version: 1.0.0
author: Mizinkobusters

commands:
  xpranking:
    permission: mining.op
    permission-message: "§cYou don't have permission todo that."
  randomstone:
    permission: mining.op
    permission-message: "§cYou don't have permission todo that."
  start:
    permission: mining.op
    permission-message: "§cYou don't have permission todo that."

permissions:
  mining.op:
    default: op